### ISSUE TITLE
Incorporate CSS column guide

### ISSUE THREAD

**Issue by mhulse** [mhulse/ps-web-starters#4]
https://gist.github.com/javasteve99/3013151

Make it mesh well with Pure css?

https://purecss.io/grids/#grids-units-sizes

```css
[grid] {
	width: 128rem;
	margin: 0 auto;
	background-size: 33rem;
	background-image: linear-gradient(
		to right, 
		rgba(255, 0, 0, 0.25) 0, 
		rgba(255, 0, 0, 0.25) 29rem, 
		transparent 29rem
	);
	background-attachment: local;
	background-origin: content-box;
	position: absolute;
	top: 0;
	right: 0;
	bottom: 0;
	left: 0;
	z-index: 999;
	pointer-events: none;
}
@media (min-width: 35.5em) {
	
}
@media (min-width: 48em) {
	
}
@media (min-width: 64em) {

}
@media (min-width: 80em) {

}
@media (min-width: 120em) {
	
}
```

```html
<div grid="4"></div>
```
